### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by Morabaraba**
- Portal all the delphi examples(7) from drezgames/raylib-pascal to fpc. Most of them run(audio scratch on linux) some raises a access violation, but all of them  compile.
- Updated readme and gitiginore.

### CODE REVIEW

**Comment by tazdij** [comment]
Oops, wrote thanks in the wrong comment box. But, thank you for the help and effort. I am currently working on fixing some of the memory issues with the materials and some other records. This should fix some of the issues in examples not working correctly.

**Comment by Morabaraba** [comment]
I just picked the low hanging fruit by converting the raylib-pascal delphi examples to raylib-lib.

I looked into raylib issue and assumed https://github.com/raysan5/raylib/issues/954 is related to our material issue?

I tried to build `2.6-dev` from raylib `master` on linux but seems im missing the x11 dev package, wip.

But very excited that audio example works on linux and macos and then most of the other. But already found some platform inconsistencies in gamepad names.

Goodluck with the materials issue, will be neat if all the examples work.

**Comment by Morabaraba** [comment]
Heh, raylib support `make` and `cmake` and the cmake build seems to statically link the x11 lib methods. 

But even `raylib 2.6-dev` seems to give me the material issue:

```sh
./models_first_person_maze 
INFO: Initializing raylib 2.6-dev
INFO: Display device initialized successfully
INFO: Display size: 1920 x 1080
INFO: Render size: 800 x 450
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: OpenGL 3.3 Core profile supported
INFO: GPU: Vendor:   nouveau
INFO: GPU: Renderer: NV137
INFO: GPU: Version:  4.3 (Core Profile) Mesa 19.0.8
INFO: GPU: GLSL:     4.30
INFO: Number of supported extensions: 204
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] ETC2/EAC compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [EXTENSION] Mirror clamp wrap texture mode supported
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: Internal buffers initialized successfully (CPU)
INFO: Internal buffers uploaded successfully (GPU)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: [res/textures/cubicmap.png] Image loaded successfully (32x16)
INFO: [TEX ID 3] Texture created successfully (32x16 - 1 mipmaps)
INFO: [VAO ID 2] Mesh uploaded successfully to VRAM (GPU)
INFO: [res/textures/cubicmap_atlas.png] Image loaded successfully (256x256)
INFO: [TEX ID 4] Texture created successfully (256x256 - 1 mipmaps)
An unhandled exception occurred at $00007F90EEB2D133:
EAccessViolation: Access violation
  $00007F90EEB2D133
  $00000000004016D3 line 46 of ../models/models_first_person_maze.pas
```

**Comment by tazdij** [comment]
Sorry for the silence. I have been super busy recently.

What version of FPC are you Using?
OS (Distro & Version)?
And are you certain it is Dynamically Linking the correct version of Raylib?

**Pull request merged**
