### PR TITLE
Add Laz Package, Fix Font Struct/Record

### PR DESCRIPTION
**Pull request by zaher**
Added Lazarus package, now just just compile this package in Lazarus, then add it to any new project, it will that paths automatically 

Fixed Crash when drawing text with font, caused with wrong Font records.

### CODE REVIEW

**Comment by zaher** [comment]
Ah I didn't noticed you are working on  2.6.0-dev not 2.5, i read version of raylib in header of raylib.pas
You can take the first commit and ignore other, 
BTW You need to make branch for 2.6-dev or branch/tag for 2.5 and keep master for dev version (that what I do), usually users use last stable version of raylib.

**Comment by raysan5** [comment]
@zaher raylib master branch is usually a stable branch, I always recommend working with that version as a developer. Released versions are targeted to users that won't touch the code... :)

**Comment by zaher** [comment]
I downloaded dll from last release of raylib, 
https://github.com/raysan5/raylib/releases

It is not compatible with your current work of raylib, 
you need to provide precompiled raylib (so, dll) for development too, that mean more work and more conflicts.
better to make branch for dev and keep merging master for other features.

**Comment by zaher** [comment]
Until now I can not find dll for version 2.6 for windows, is there in raylib snapshots builds?

**Comment by tazdij** [comment]
Hey there, currently there are no dlls available for the version of raylib we target. You will need to download the raylib source and compile it yourself.On Nov 24, 2019 07:15, Zaher Dirkey <notifications@github.com> wrote:Until now I can not find dll for version 2.6 for windows, is there in raylib snapshots builds?

**Comment by tazdij** [comment]
We try to maintain as close as possible to raylib master. Master is always dev, and once raylib is released again as stable (2.6), we will also release a stable for that version. And will continue developmemt on master. I do not want to spend any time making a stable release for an old version (2.5) of raylib.On Nov 24, 2019 06:51, Zaher Dirkey <notifications@github.com> wrote:I downloaded dll from last release of raylib,
https://github.com/raysan5/raylib/releases
It is not compatible with your current work of raylib,
you need to provide precompiled raylib (so, dll) for development too, that mean more work and more conflicts.
better to make branch for dev and keep merging master for other features.

**Comment by tazdij** [comment]
This pr cannot be accepted. The changes you have made to the raylib.pas file are incorrect, and will break the memory layout when working with the 2.6-dev dll. The changes you made are sort of how it was in 2.5, which we are not targeting in this binding.

**Comment by tazdij** [comment]
Please create a pr with only the pkg file for Lazarus and i can accept that. Thanks.

**Pull request closed without merging**
